In [2]:
import pandas as pd
import pathlib

In [19]:
src = pathlib.Path().cwd().parent.parent / 'data' / 'external' / 'treatment-data'
current_date = '2021-08-19'
column_name = [
    'level',
    'no',
    'hospital',
    'no_bed',
    'no_positive',
    'no_positive_treating',
    'no_positive_children',
    'no_positive_pregnant',
    'no_positive_else',
    'no_positive_cs',
    'no_mild_not_comorbidity',
    'no_mild_stable_comorbidity',
    'no_in',
    'no_up',
    'no_down',
    'no_out',
    'no_out_cs',
    'no_death',
    'no_death_cs',
    'no_death_other_causes',
    'no_test_tomorrow',
    'no_ecmo_total',
    'no_ecmo_in_use',
    'no_dialysis_total',
    'no_dialysis_in_use',
    'no_ivent_total',
    'no_ivent_in_use',
    'no_hfnc_total',
    'no_hfnc_in_use',
    'no_cpap_total',
    'no_cpap_in_use',
    'no_bipap_total',
    'no_bipap_in_use',
    'no_mask_total',
    'no_mask_in_use',
    'no_oxy_total',
    'no_oxy_in_use'
]

In [22]:
df = pd.read_excel(
    src / (current_date + '.xlsx'),
    skiprows=3,
    header=0
)
df.columns = column_name
df['date_report'] = pd.to_datetime(current_date)

In [37]:
df.tail(10)
df_summary = df.iloc[-5:,:]
df_1 = df.iloc[:-5,:]

In [40]:
df_summary
# df_1.tail()

,level,no,hospital,no_bed,no_positive,no_positive_treating,no_positive_children,no_positive_pregnant,no_positive_else,no_positive_cs,...,no_hfnc_in_use,no_cpap_total,no_cpap_in_use,no_bipap_total,no_bipap_in_use,no_mask_total,no_mask_in_use,no_oxy_total,no_oxy_in_use,date_report
99,NaN,NaN,TỔNG CỘNG:,59596,41193,38174,3459,345,34370,220652,...,1286,228,91,98,24,9094,5111,13232,7890,2021-09-19
100,NaN,NaN,Tổng Tầng 2 :,55507,38025,35067,3442,336,31289,209516,...,821,190,73,86,22,7334,4050,9883,5734,2021-09-19
101,NaN,NaN,Tổng Tầng 3 :,4089,3168,3107,17,9,3081,11136,...,465,38,18,12,2,1760,1061,3349,2156,2021-09-19
102,NaN,NaN,Tỉ lệ phần trăm theo Tầng 2 :,93,92,99,97,91,91,94,...,63,83,80,87,91,80,79,74,72,2021-09-19
103,NaN,NaN,Tỉ lệ phần trăm theo Tầng 3 :,6,7,0,2,8,8,5,...,36,16,19,12,8,19,20,25,27,2021-09-19